#!/bin/bash

# AlphaZero Capital - OpenRouter Quick Setup
# Sets up the system to use OpenRouter in 2 minutes

set -e

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🚀 AlphaZero Capital - OpenRouter Quick Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

# Check if .env exists
if [ -f ".env" ]; then
    echo "⚠️  .env file already exists!"
    read -p "   Overwrite with OpenRouter config? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "   Cancelled. Your .env file was not modified."
        exit 0
    fi
fi

# Ask for OpenRouter API key
echo "📝 OpenRouter Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Don't have an OpenRouter API key yet?"
echo "   1. Go to: https://openrouter.ai"
echo "   2. Sign up (free)"
echo "   3. Go to Keys section"
echo "   4. Create new API key"
echo "   5. Copy the key (starts with sk-or-v1-...)"
echo ""

read -p "Enter your OpenRouter API key: " api_key

if [ -z "$api_key" ]; then
    echo "❌ No API key provided. Exiting."
    exit 1
fi

# Validate key format
if [[ ! $api_key =~ ^sk-or-v1- ]]; then
    echo "⚠️  Warning: Key doesn't start with 'sk-or-v1-'"
    echo "   Make sure you copied the correct key from OpenRouter"
    read -p "   Continue anyway? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 0
    fi
fi

echo ""
echo "🤖 Choose Your AI Model"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Popular models for trading:"
echo ""
echo "1) Claude 3 Sonnet (RECOMMENDED)"
echo "   ★★★★★ Best balance of quality and cost"
echo "   Cost: ~$54/month for typical trading"
echo ""
echo "2) Llama 3 70B (CHEAPEST QUALITY)"
echo "   ★★★★☆ Excellent open-source model"
echo "   Cost: ~$3/month for typical trading"
echo ""
echo "3) Gemini Pro (BEST VALUE)"
echo "   ★★★★☆ Google's model, great value"
echo "   Cost: ~$6/month for typical trading"
echo ""
echo "4) GPT-4 Turbo (MOST POWERFUL)"
echo "   ★★★★★ Most intelligent, expensive"
echo "   Cost: ~$120/month for typical trading"
echo ""
echo "5) Mixtral 8x7B (FASTEST)"
echo "   ★★★★☆ Very fast, cheap"
echo "   Cost: ~$6/month for typical trading"
echo ""
echo "6) Custom (enter model name manually)"
echo ""

read -p "Choose model (1-6): " model_choice

case $model_choice in
    1)
        model="anthropic/claude-3-sonnet"
        model_name="Claude 3 Sonnet"
        ;;
    2)
        model="meta-llama/llama-3-70b-instruct"
        model_name="Llama 3 70B"
        ;;
    3)
        model="google/gemini-pro"
        model_name="Gemini Pro"
        ;;
    4)
        model="openai/gpt-4-turbo"
        model_name="GPT-4 Turbo"
        ;;
    5)
        model="mistralai/mixtral-8x7b-instruct"
        model_name="Mixtral 8x7B"
        ;;
    6)
        echo ""
        echo "See all models at: https://openrouter.ai/models"
        read -p "Enter model name (e.g., anthropic/claude-3-sonnet): " model
        model_name="$model"
        ;;
    *)
        echo "Invalid choice. Using default: Claude 3 Sonnet"
        model="anthropic/claude-3-sonnet"
        model_name="Claude 3 Sonnet"
        ;;
esac

echo ""
echo "✅ Selected: $model_name"
echo ""

# Create .env file
echo "📝 Creating .env file..."

cat > .env << EOF
# AlphaZero Capital - OpenRouter Configuration
# Auto-generated by setup_openrouter.sh

# ==========================================
# AI PROVIDER - OPENROUTER
# ==========================================

LLM_PROVIDER=openrouter
OPENROUTER_API_KEY=$api_key
OPENROUTER_MODEL=$model

# ==========================================
# TRADING MODE
# ==========================================

MODE=PAPER
# Start in paper mode (no real money)

INITIAL_CAPITAL=1000000
# ₹10L virtual capital for testing

ITERATION_INTERVAL=900
# 15 minutes between trading loops

# ==========================================
# RISK MANAGEMENT
# ==========================================

MAX_DAILY_LOSS_PCT=0.02
MAX_POSITION_SIZE_PCT=0.05
MAX_SECTOR_EXPOSURE_PCT=0.30
MAX_POSITIONS=10
MAX_TRADES_PER_DAY=20
CONSECUTIVE_LOSS_LIMIT=3

# ==========================================
# TRAILING STOPS
# ==========================================

ACTIVATION_PROFIT_PCT=0.02
TRAIL_ATR_MULTIPLIER=1.5
TRAIL_PCT=0.03

# ==========================================
# FEATURES
# ==========================================

ENABLE_OPTIONS_FLOW=true
ENABLE_MULTI_TIMEFRAME=true
ENABLE_TRAILING_STOPS=true
ENABLE_LLM_AGENTS=true
ENABLE_STRATEGY_DISCOVERY=true

# ==========================================
# DATA STORAGE
# ==========================================

DATABASE_URL=sqlite:///data/alphazero.db
REDIS_URL=redis://localhost:6379/0

# ==========================================
# MONITORING
# ==========================================

LOG_LEVEL=INFO
ENABLE_DASHBOARD=true
DASHBOARD_PORT=8501

# ==========================================
# TELEGRAM (Optional - leave blank if not using)
# ==========================================

TELEGRAM_BOT_TOKEN=
TELEGRAM_CHAT_ID=

# ==========================================
# OPENALGO (Optional - for live trading only)
# ==========================================

OPENALGO_API_KEY=
OPENALGO_URL=http://localhost:5000
EOF

echo "   ✅ .env file created"
echo ""

# Install OpenAI package (needed for OpenRouter)
echo "📦 Installing required package..."
if command -v pip &> /dev/null; then
    pip install openai --quiet && echo "   ✅ openai package installed" || echo "   ⚠️  Failed to install openai (install manually: pip install openai)"
else
    echo "   ⚠️  pip not found. Install manually: pip install openai"
fi
echo ""

# Update llm_provider.py if exists
if [ -f "src/llm/llm_provider.py" ]; then
    echo "📝 Checking LLM provider..."
    if grep -q "OpenRouterProvider" src/llm/llm_provider.py; then
        echo "   ✅ OpenRouter support already present"
    else
        echo "   ⚠️  llm_provider.py needs updating"
        echo "   Replace with: llm_provider_with_openrouter.py (provided in files)"
    fi
else
    echo "   ℹ️  src/llm/llm_provider.py not found"
    echo "   Make sure you have the complete AlphaZero package"
fi
echo ""

# Test the configuration
echo "🧪 Testing OpenRouter connection..."
python << 'PYEOF' 2>/dev/null
import sys
import os
from dotenv import load_dotenv

load_dotenv()

try:
    # Test import
    from src.llm.llm_provider import LLMProvider
    
    # Test connection
    provider = LLMProvider.create('openrouter')
    
    print(f"\n   ✅ Provider created successfully")
    print(f"   Model: {provider.model}")
    
    # Quick test
    response = provider.chat("Reply with exactly: 'OpenRouter connected!'", max_tokens=20)
    
    if "connected" in response.lower() or "openrouter" in response.lower():
        print(f"   ✅ API test successful!")
        print(f"\n   Response: {response[:100]}")
    else:
        print(f"   ⚠️  Got response but unexpected: {response[:50]}")
        
except Exception as e:
    print(f"   ❌ Test failed: {e}")
    print(f"\n   This is OK if you haven't installed all packages yet.")
    print(f"   Run: pip install -r requirements.txt")
    sys.exit(0)
PYEOF

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ OpenRouter Setup Complete!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 Configuration Summary:"
echo "   • Provider: OpenRouter"
echo "   • Model: $model_name"
echo "   • Mode: Paper trading (₹10L virtual)"
echo "   • All features: Enabled"
echo ""
echo "🚀 Next Steps:"
echo ""
echo "   1. Install all requirements (if not done):"
echo "      pip install -r requirements.txt"
echo ""
echo "   2. Make sure Redis is running:"
echo "      redis-server"
echo ""
echo "   3. Start trading:"
echo "      python main.py"
echo ""
echo "   4. Open dashboard (optional):"
echo "      streamlit run src/dashboard/app.py"
echo ""
echo "💡 Tips:"
echo "   • Monitor costs at: https://openrouter.ai/activity"
echo "   • Switch models anytime by editing .env"
echo "   • Start with paper mode for 3 months minimum"
echo ""
echo "📚 Documentation:"
echo "   • Read: OPENROUTER_COMPLETE_GUIDE.md"
echo "   • All models: https://openrouter.ai/models"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Happy trading! 🎉📈💰"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
