import sys, os, time
ROOT = os.getcwd()
sys.path.append(ROOT)

def test_import(name, module_path):
    print(f"Testing {name}...", end="", flush=True)
    try:
        start = time.time()
        exec(f"import {module_path}")
        print(f" OK ({time.time()-start:.2f}s)")
    except Exception as e:
        print(f" FAILED: {e}")

print("DIAGNOSTIC IMPORT TEST")
test_import("Settings", "config.settings")
test_import("EventBus", "src.event_bus.event_bus")
test_import("ChiefAgent", "src.agents.chief_agent")
test_import("SigmaAgent", "src.agents.sigma_agent")
test_import("SectorAgent", "src.agents.sector_agent")
test_import("OracleAgent", "src.agents.oracle_agent")
test_import("IntradayRegime", "src.agents.intraday_regime_agent")
test_import("NewsSentiment", "src.agents.news_sentiment_agent")
test_import("Titan", "src.agents.titan_agent")
test_import("Guardian", "src.agents.guardian_agent")
test_import("Mercury", "src.agents.mercury_agent")
test_import("Lens", "src.agents.lens_agent")
test_import("Karma", "src.agents.karma_agent")
test_import("OptionsFlow", "src.agents.options_flow_agent")
test_import("MultiTimeframe", "src.agents.multi_timeframe_agent")
test_import("EarningsAnalyzer", "src.agents.llm_earnings_analyzer")
test_import("StrategyGenerator", "src.agents.llm_strategy_generator")
test_import("LLMProvider", "src.agents.llm_provider")
test_import("RiskManager", "src.risk.risk_manager")
test_import("DataFetcher", "src.data.fetch")
test_import("MarketDataEngine", "src.data.market_data")
print("Done.")
