import logging
from typing import Dict, List, Any
from datetime import datetime
import uuid
from dataclasses import asdict

try:
    from src.event_bus.event_bus import BaseAgent, EventType
except ImportError:
    try:
        from ..event_bus.event_bus import BaseAgent, EventType
    except ImportError:
        # Fallback for static analysis tools
        class BaseAgent:
            def __init__(self, event_bus=None, config=None, name=""):
                self.event_bus = event_bus; self.config = config or {}; self.name = name
                self.is_active = True; self.last_activity = "Initialised"
            def publish_event(self, *a, **k): pass
            def subscribe(self, *a, **k): pass
        class EventType:
            SIGNAL_GENERATED = "signal_generated"
            TRADE_EXECUTED = "trade_executed"
            SIGNAL_EVALUATED = "signal_evaluated"
from ..evaluator import EvaluationEngine, SignalRecord

logger = logging.getLogger(__name__)


class LensAgent(BaseAgent):
    """
    LENS - Performance Attribution Agent

    Responsibilities:
    - Track P&L per trade
    - Evaluate ALL signals (paper trading evaluation)
    - Strategy performance attribution
    - Award points and lessons for KARMA (RL)
    - Daily/weekly/monthly reports

    KPI: Daily report generated by 8 PM IST
    """

    def __init__(self, event_bus, config):
        super().__init__(event_bus=event_bus, config=config, name="LENS")

        # Performance tracking (Actual trades)
        self.trades: List[Dict] = []
        self.daily_pnl: List[float] = []
        self.strategy_performance: Dict[str, Dict] = {}

        # Metrics
        self.total_pnl = 0.0
        self.winning_trades = 0
        self.losing_trades = 0
        self.filled_ids: set[str] = set()

        # Evaluation Engine (Signal paper tracking)
        self.evaluator = EvaluationEngine()
        self._current_prices: Dict[str, float] = {}

        # Subscriptions
        self.subscribe(EventType.SIGNAL_GENERATED, self._on_signal_generated)
        self.subscribe(EventType.TRADE_EXECUTED,   self._on_trade_executed)

        logger.info("LENS Agent initialized - Evaluation & Performance tracking ready")

    def _on_trade_executed(self, event):
        """Mark a signal as 'filled' so LENS logs its evaluation publicly."""
        p = event.payload
        sig_id = p.get('signal_id')
        if sig_id:
            self.filled_ids.add(sig_id)
            # Update evaluator with actual fill price for accurate P&L tracking
            fill_price = p.get('price')
            if fill_price:
                self.evaluator.update_fill_price(sig_id, fill_price)
            logger.debug(f"LENS: marked signal {sig_id} as FILLED at ₹{fill_price}")

    def _on_signal_generated(self, event):
        """Log every generated signal for evaluation."""
        p = event.payload
        # Convert event payload (Signal) to SignalRecord
        try:
            # Generate a unique ID if not present
            sig_id = p.get('id', str(uuid.uuid4())[:8])
            
            # Map signal action (BUY/SELL) to direction (+1/-1)
            action = p.get('signal') or p.get('action') or 'BUY'
            direction = 1 if action == 'BUY' else -1

            record = SignalRecord(
                id=sig_id,
                symbol=p.get('symbol'),
                strategy_id=p.get('source', 'TITAN'),
                strategy_name=p.get('strategy_name', p.get('source', 'TITAN')),
                agent=p.get('source', 'TITAN'),
                direction=direction,
                confidence=p.get('confidence', 0.5),
                entry_price=p.get('price', 0.0) or p.get('entry_price', 0.0),
                stop_loss=p.get('stop_loss', 0.0),
                target=p.get('target', 0.0),
                regime=p.get('regime', 'UNKNOWN'),
                trade_type=p.get('trade_type', 'SWING'),
                emitted_at=datetime.now().isoformat()
            )
            self.evaluator.log_signal(record)
        except Exception as e:
            logger.warning(f"LENS: failed to log signal for evaluation: {e}")

    def record_trade(self, trade: Dict[str, Any]):
        """Record a completed trade (actual execution) and update running metrics."""
        self.trades.append({
            **trade,
            'recorded_at': datetime.now().isoformat()
        })

        pnl = trade.get('pnl', 0)
        self.total_pnl += pnl

        # WIN only if pnl_pct > +0.2% (USER REQUEST)
        pnl_pct = trade.get('pnl_pct', trade.get('realised_pct', 0))
        if pnl_pct > 0.2:
            self.winning_trades += 1
        elif pnl_pct < -0.2:
            self.losing_trades += 1
            
        strategy = trade.get('strategy', 'unknown')
        if strategy not in self.strategy_performance:
            self.strategy_performance[strategy] = {
                'trades': 0, 'pnl': 0.0, 'wins': 0, 'losses': 0
            }

        sp = self.strategy_performance[strategy]
        sp['trades'] += 1
        sp['pnl'] += pnl
        if pnl_pct > 0.2:
            sp['wins'] += 1
        elif pnl_pct < -0.2:
            sp['losses'] += 1

        logger.info(f"LENS recorded actual trade: {trade.get('symbol')} P&L: ₹{pnl:,.0f}")

    def update_prices(self, prices: Dict[str, float]):
        """Update local price cache for evaluation engine."""
        self._current_prices.update(prices)

    def update(self):
        """
        Periodic evaluation — called each main loop iteration.
        Resolves pending signals and broadcasts outcomes.
        """
        if not self._current_prices:
            return

        # Enforce minimum holding time from config (e.g., 10 mins)
        min_h = self.config.get('MIN_HOLDING_TIME_M', 10)
        evaluated = self.evaluator.evaluate_pending(self._current_prices, min_holding_time_m=min_h)
        
        for rec in evaluated:
            # Only count as official winner/loser if it was actually FILLED
            is_filled = rec.id in self.filled_ids
            
            if not is_filled:
                # Log as PENDING (observed but not traded)
                logger.info(f"🔍 LENS Signal Observation: {rec.symbol} {rec.outcome} | (NOT EXECUTED -> SIGNAL ONLY)")
                continue

            signal_data = {
                'strategy': rec.strategy_id,
                'symbol': rec.symbol,
                'regime': rec.regime,
                'source': rec.agent,
                'confidence': rec.confidence
            }
            outcome_data = {
                'pnl': rec.actual_pnl_pct or 0.0,
                'event': f"eval_{rec.outcome.lower()}",
                'symbol': rec.symbol,
                'points': rec.points_awarded,
                'lesson': rec.lesson
            }
            
            # Publish evaluation event for KARMA to consume
            self.publish_event(
                EventType.SIGNAL_EVALUATED,
                {
                    'signal': signal_data,
                    'outcome': outcome_data,
                    'record': asdict(rec) if hasattr(rec, 'asdict') else rec.__dict__
                }
            )
            
            # Log to terminal (only for executed trades now)
            logger.info(f"🎯 LENS Evaluation: {rec.symbol} {rec.outcome} | P&L: {rec.actual_pnl_pct:+.2f}% | Pts: {rec.points_awarded:+.1f}")

    def generate_daily_report(self) -> Dict[str, Any]:
        """Generate daily performance report."""
        total_trades = self.winning_trades + self.losing_trades
        win_rate = (self.winning_trades / total_trades) if total_trades > 0 else 0.0

        report = {
            'date': datetime.now().date().isoformat(),
            'total_pnl': self.total_pnl,
            'total_trades': total_trades,
            'winning_trades': self.winning_trades,
            'losing_trades': self.losing_trades,
            'win_rate': win_rate,
            'avg_win': self._calculate_avg_win(),
            'avg_loss': self._calculate_avg_loss(),
            'profit_factor': self._calculate_profit_factor(),
            'strategy_breakdown': self.strategy_performance,
            'evaluator_stats': self.evaluator.get_dashboard_stats()
        }

        logger.info(
            f"LENS daily report: {total_trades} trades, "
            f"Win rate: {win_rate:.1%}, P&L: ₹{self.total_pnl:,.0f}"
        )
        return report

    def get_performance_summary(self) -> Dict[str, Any]:
        """Return a concise performance summary suitable for display / logging."""
        total_trades = self.winning_trades + self.losing_trades
        win_rate = (self.winning_trades / total_trades) if total_trades > 0 else 0.0

        return {
            'total_pnl': self.total_pnl,
            'total_trades': total_trades,
            'win_rate': win_rate,
            'profit_factor': self._calculate_profit_factor(),
            'best_strategy': self._best_strategy(),
            'evaluator_stats': self.evaluator.get_dashboard_stats()
        }

    def _best_strategy(self) -> str:
        """Return the strategy with the highest total P&L."""
        if not self.strategy_performance:
            return 'N/A'
        return max(
            self.strategy_performance,
            key=lambda s: self.strategy_performance[s]['pnl']
        )

    def _calculate_avg_win(self) -> float:
        wins = [t['pnl'] for t in self.trades if t.get('pnl', 0) > 0]
        return sum(wins) / len(wins) if wins else 0.0

    def _calculate_avg_loss(self) -> float:
        losses = [t['pnl'] for t in self.trades if t.get('pnl', 0) < 0]
        return sum(losses) / len(losses) if losses else 0.0

    def _calculate_profit_factor(self) -> float:
        """Gross profit / gross loss (0 if no losses)."""
        gross_profit = sum(t['pnl'] for t in self.trades if t.get('pnl', 0) > 0)
        gross_loss = abs(sum(t['pnl'] for t in self.trades if t.get('pnl', 0) < 0))
        return (gross_profit / gross_loss) if gross_loss > 0 else 0.0

    def get_stats(self) -> Dict[str, Any]:
        """Get LENS statistics."""
        total_trades = self.winning_trades + self.losing_trades
        win_rate = (self.winning_trades / total_trades) if total_trades > 0 else 0.0

        return {
            'name': self.name,
            'active': self.is_active,
            'total_pnl': self.total_pnl,
            'total_trades': total_trades,
            'win_rate': win_rate,
            'eval_pending': len(self.evaluator._pending),
            'kpi': 'Daily report by 8 PM IST'
        }
