"""
LENS Agent - Performance Attribution

Tracks performance, generates reports, and attributes P&L.
The system's accountant and analyst.

FIXES:
- Removed markdown header block (lines 1-5 + closing ```) that caused SyntaxError
- Added missing get_performance_summary() method
"""

import logging
from typing import Dict, List, Any
from datetime import datetime

from ..event_bus.event_bus import BaseAgent, EventType

logger = logging.getLogger(__name__)


class LensAgent(BaseAgent):
    """
    LENS - Performance Attribution Agent

    Responsibilities:
    - Track P&L per trade
    - Strategy performance attribution
    - Daily/weekly/monthly reports
    - Win rate calculation
    - Sharpe ratio tracking

    KPI: Daily report generated by 8 PM IST
    """

    def __init__(self, event_bus, config):
        super().__init__(event_bus=event_bus, config=config, name="LENS")

        # Performance tracking
        self.trades: List[Dict] = []
        self.daily_pnl: List[float] = []
        self.strategy_performance: Dict[str, Dict] = {}

        # Metrics
        self.total_pnl = 0.0
        self.winning_trades = 0
        self.losing_trades = 0

        logger.info("LENS Agent initialized - Performance tracking ready")

    def record_trade(self, trade: Dict[str, Any]):
        """Record a completed trade and update running metrics."""
        self.trades.append({
            **trade,
            'recorded_at': datetime.now().isoformat()
        })

        pnl = trade.get('pnl', 0)
        self.total_pnl += pnl

        if pnl > 0:
            self.winning_trades += 1
        elif pnl < 0:
            self.losing_trades += 1

        strategy = trade.get('strategy', 'unknown')
        if strategy not in self.strategy_performance:
            self.strategy_performance[strategy] = {
                'trades': 0, 'pnl': 0.0, 'wins': 0, 'losses': 0
            }

        sp = self.strategy_performance[strategy]
        sp['trades'] += 1
        sp['pnl'] += pnl
        if pnl > 0:
            sp['wins'] += 1
        elif pnl < 0:
            sp['losses'] += 1

        logger.info(f"LENS recorded trade: {trade.get('symbol')} P&L: ₹{pnl:,.0f}")

    def generate_daily_report(self) -> Dict[str, Any]:
        """Generate daily performance report."""
        total_trades = self.winning_trades + self.losing_trades
        win_rate = (self.winning_trades / total_trades) if total_trades > 0 else 0.0

        report = {
            'date': datetime.now().date().isoformat(),
            'total_pnl': self.total_pnl,
            'total_trades': total_trades,
            'winning_trades': self.winning_trades,
            'losing_trades': self.losing_trades,
            'win_rate': win_rate,
            'avg_win': self._calculate_avg_win(),
            'avg_loss': self._calculate_avg_loss(),
            'profit_factor': self._calculate_profit_factor(),
            'strategy_breakdown': self.strategy_performance
        }

        logger.info(
            f"LENS daily report: {total_trades} trades, "
            f"Win rate: {win_rate:.1%}, P&L: ₹{self.total_pnl:,.0f}"
        )
        return report

    def get_performance_summary(self) -> Dict[str, Any]:
        """
        Return a concise performance summary suitable for display / logging.

        FIXES: This method was referenced elsewhere but was missing.
        """
        total_trades = self.winning_trades + self.losing_trades
        win_rate = (self.winning_trades / total_trades) if total_trades > 0 else 0.0

        return {
            'total_pnl': self.total_pnl,
            'total_trades': total_trades,
            'win_rate': win_rate,
            'profit_factor': self._calculate_profit_factor(),
            'best_strategy': self._best_strategy()
        }

    def _best_strategy(self) -> str:
        """Return the strategy with the highest total P&L."""
        if not self.strategy_performance:
            return 'N/A'
        return max(
            self.strategy_performance,
            key=lambda s: self.strategy_performance[s]['pnl']
        )

    def _calculate_avg_win(self) -> float:
        wins = [t['pnl'] for t in self.trades if t.get('pnl', 0) > 0]
        return sum(wins) / len(wins) if wins else 0.0

    def _calculate_avg_loss(self) -> float:
        losses = [t['pnl'] for t in self.trades if t.get('pnl', 0) < 0]
        return sum(losses) / len(losses) if losses else 0.0

    def _calculate_profit_factor(self) -> float:
        """Gross profit / gross loss (0 if no losses)."""
        gross_profit = sum(t['pnl'] for t in self.trades if t.get('pnl', 0) > 0)
        gross_loss = abs(sum(t['pnl'] for t in self.trades if t.get('pnl', 0) < 0))
        return (gross_profit / gross_loss) if gross_loss > 0 else 0.0

    def update(self):
        """Periodic housekeeping — called each main loop iteration."""
        pass  # LENS updates reactively via record_trade(); nothing to poll

    def get_stats(self) -> Dict[str, Any]:
        """Get LENS statistics."""
        total_trades = self.winning_trades + self.losing_trades
        win_rate = (self.winning_trades / total_trades) if total_trades > 0 else 0.0

        return {
            'name': self.name,
            'active': self.is_active,
            'total_pnl': self.total_pnl,
            'total_trades': total_trades,
            'win_rate': win_rate,
            'kpi': 'Daily report by 8 PM IST'
        }
